from . import (stable_horse,
               stable_competition,
               stable_health,
               mrp_production,
               stable_vaccins,
               stable_osteopath,
               stable_dentist,
               stable_farrier,
               stable_veterinary,
               stable_horse_tag,
               )
